# Task 4
- Group: 36
- Candidate number: 4, 49, 63, 82

This function takes a 2D numpy array (matrix) as input and checks whether
it is square, meaning the number of rows and columns are equal. If the matrix
is square, it calculates and returns the trace - which is the sum of the
elements along the main diagonal.

In [2]:
import numpy as np

def trace(a):
    rows = a.shape[0]
    cols = a.shape[1]

    if rows != cols: # Checks that columns coincide with the number of rows
        print(f"Matrix: \n{a}\nis not square")
        print(f"Rows: {rows}",)
        print(f"Columns: {cols}\n")
        return None

    diagonal_sum = 0
    for i in range(rows):
        diagonal_sum += a[i, i] # Add diagonal element where row index equals column index

    print(f"Matrix:\n{a}\n has a diagonal sum of: {diagonal_sum}\n")
    return diagonal_sum


# Test with a non-square 2d array
a = np.array([[1, 2, 3],
              [4, 5, 6]])
test_a = trace(a)

# Test with the 2d array given in the problem description
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
test_b = trace(b)

# Test with another 2d array
c = np.array([[2, 6, 1],
              [3, 5, 16],
              [17, 28, 39]])

test_c = trace(c)

# Test with a 4x4 square matrix
d = np.array([[1, 2, 3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
test_d = trace(d)

Matrix: 
[[1 2 3]
 [4 5 6]]
is not square
Rows: 2
Columns: 3

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 has a diagonal sum of: 15

Matrix:
[[ 2  6  1]
 [ 3  5 16]
 [17 28 39]]
 has a diagonal sum of: 46

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
 has a diagonal sum of: 34

